
version : '3'
services:
  mysqldatabase:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    ports:
      - 3307:3306
    networks:
      - backend-net
    volumes:
      - my-db:/var/lib/mysql


  kaddem-app:
    image : melekboug/kaddem:1.0
    depends_on:
      - mysqldatabase
    restart: on-failure
    ports:
      - 9988:9988
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldatabase:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.show-sql" : "true",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect"
          }'
    networks:
      - backend-net


networks:
  backend-net :

volumes:
  my-db:
    driver: local
